config/routes.rb
Rails.application.routes.draw do
  resources :patients

  resources :physicians

  resources :appointments

  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :homes

  root 'homes#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :physician
  belongs_to :patient
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  respond_to :html,:json

  def index
    @events = []
    user_type_id = current_user.meta_id
    user_type = current_user.meta_type
    if(user_type =="Patient")
      patient = Patient.find_by_id(user_type_id)
      @appointments = patient.appointments
    elsif(user_type =="Doctor")
      doctor = Doctor.find_by_id(user_type_id)
      @appointments = doctor.appointments
    end
    @doctors  = Doctor.all
    @appointments.each do |app|
      puts app.inspect
      @events << {:id => app.id, :title => "#{app.name} : #{app.reason}", :start => app.start,:end => app.end }
    end
    respond_with(@events)
  end

  def show
    respond_with(@appointment)
  end

  def new
    @doctorId = params[:doctorId]
    @appointment = Appointment.new
    respond_with(@appointment)
  end

  def edit
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.patient_id = params["patient_id"]
    @appointment.doctor_id = params["physician_id"]
    @appointment.save
    respond_with(@appointment)
  end

  def update
    @appointment.update(appointment_params)
    respond_with(@appointment)
  end

  def destroy
    @appointment.destroy
    respond_with(@appointment)
  end

  private
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    def appointment_params
      params.require(:appointment).permit(:name, :reason, :start, :end, :email, :mobile)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_field :reason %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.datetime_select :start%>

  </div>
    <div class="field">
      <%= f.label :end %><br>
      <%= f.datetime_select :end %>

    </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
    <%= hidden_field_tag 'patient_id', current_user.meta_id %>
    <%= hidden_field_tag 'physician_id', @doctorId %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<script>
    $(document).ready(function(){
        $('#new_event').click(function(event) {
            event.preventDefault();
            var url = $(this).attr('href');
            alert(url);
            $.ajax({
                url: url,
                beforeSend: function() {
                    $('#loading').show();
                },
                complete: function() {
                    $('#loading').hide();
                },
                success: function(data) {
                    $('#create_event').replaceWith(data['form']);
                    $('#create_event_dialog').dialog({
                        title: 'New Event',
                        modal: true,
                        width: 500,
                        close: function(event, ui) { $('#create_event_dialog').dialog('destroy') }
                    });
                }
            });
        });
        $('#calendar').fullCalendar({
            editable: true,
            header: {
                left: 'today prev,next',
                center: 'title',
                right: 'month,agendaWeek,agendaDay'
            },
            defaultView: 'month',
            height: 400,
            slotMinutes: 15,
            loading: function(bool){
                if (bool)
                    $('#loading').show();
                else
                    $('#loading').hide();
            },
            events: "/appointments.json",
            timeFormat: 'h:mm T ',
            lazyFetching: true,
            dragOpacity: "0.5",
            eventDrop: function(event, dayDelta, minuteDelta, allDay, revertFunc){
//              if (confirm("Are you sure about this change?")) {
                moveEvent(event, dayDelta, minuteDelta, allDay);
//              }
//              else {
//                  revertFunc();
//              }
            },

            eventResize: function(event, dayDelta, minuteDelta, revertFunc){
//              if (confirm("Are you sure about this change?")) {
                resizeEvent(event, dayDelta, minuteDelta);
//              }
//              else {
//                  revertFunc();
//              }
            },

            eventClick: function(event, jsEvent, view){
                showEventDetails(event);
            }
        });
    });
</script>
<div>
  <div id='calendar'>
  </div>
</div>
<div id = "desc_dialog" class="dialog" style ="display:none;">
  <div id = "event_desc">
  </div>
  <br/>
  <br/>
  <div id = "event_actions">
    <span id = "edit_event"></span>
    <span id = "delete_event"></span>
  </div>
</div>
<div id = "create_event_dialog" class="dialog" style ="display:none;">
  <div id = "create_event">
  </div>
</div>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @appointment.name %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @appointment.reason %>
</p>

<p>
  <strong>Start:</strong>
  <%= @appointment.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @appointment.end %>
</p>

<p>
  <strong>Email:</strong>
  <%= @appointment.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @appointment.mobile %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>